In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
from re import search

In [14]:


DataA = "Final_House_data.csv"
#DataB = "SCRAPPING Inmuebles 24/Propiedades Inmuebles Todo Mexico2.csv"


# Read CSVs and store into Pandas data frames
DataA_DF = pd.read_csv(DataA)
#DataB_DF = pd.read_csv(DataB)


In [ ]:
DataA_DF

In [16]:
DataA_DF.dtypes

Unnamed: 0                 int64
Marca                     object
Clasificacion             object
Tipo                      object
Estado                    object
Municipio                 object
Colonia                   object
Colonia2                  object
Street                    object
Price                     object
Moneda                    object
PriceClean                 int64
Price MXN                float64
Superficie_Terreno         int64
Superficie_Construida      int64
Recamaras                  int64
Banos                      int64
Medio_Bano                 int64
Estacionamientos           int64
CordA                     object
URL                       object
Lat                      float64
Lon                      float64
geometry                  object
OBJECTID_x                 int64
CVEGEO                    object
CVE_ENT_x                  int64
CVE_MUN_x                  int64
CVE_LOC_x                float64
CVE_AGEB_x                object
Ambito    

In [17]:
for i, row in DataA_DF.iterrows():
    Banos = str(row["Banos"])
    #Columna Terreno
    try:
        if len(Banos) <= 1:
            New_Banos = Banos
            DataA_DF.at[i,'Banos'] = New_Banos
        else:
            #if len(Banos) == 1:
            New_Banos = Banos[0]
            DataA_DF.at[i,'Banos'] = New_Banos
            #else:
             #   pass
    except:
        New_Banos = Banos
        DataA_DF.at[i,'Banos'] = New_Banos

In [20]:
for i, row in DataA_DF.iterrows():
    Banos = str(row["Recamaras"])
    #Columna Terreno
    try:
        if len(Banos) <= 1:
            New_Banos = Banos
            DataA_DF.at[i,'Recamaras'] = New_Banos
        else:
            #if len(Banos) == 1:
            New_Banos = Banos[0]
            DataA_DF.at[i,'Recamaras'] = New_Banos
            #else:
             #   pass
    except:
        New_Banos = Banos
        DataA_DF.at[i,'Recamaras'] = New_Banos

In [23]:
for i, row in DataA_DF.iterrows():
    Banos = str(row["Medio_Bano"])
    #Columna Terreno
    try:
        if len(Banos) <= 1:
            New_Banos = Banos
            DataA_DF.at[i,'Medio_Bano'] = New_Banos
        else:
            #if len(Banos) == 1:
            New_Banos = Banos[0]
            DataA_DF.at[i,'Medio_Bano'] = New_Banos
            #else:
             #   pass
    except:
        New_Banos = Banos
        DataA_DF.at[i,'Medio_Bano'] = New_Banos

In [25]:
for i, row in DataA_DF.iterrows():
    Banos = str(row["Estacionamientos"])
    #Columna Terreno
    try:
        if len(Banos) <= 1:
            New_Banos = Banos
            DataA_DF.at[i,'Estacionamientos'] = New_Banos
        else:
            #if len(Banos) == 1:
            New_Banos = Banos[0]
            DataA_DF.at[i,'Estacionamientos'] = New_Banos
            #else:
             #   pass
    except:
        New_Banos = Banos
        DataA_DF.at[i,'Estacionamientos'] = New_Banos

In [18]:
DataA_DF['Banos'].unique()

array([2, 3, 4, 8, 1, 0, 5, 6, 7, 9])

In [21]:
DataA_DF['Recamaras'].unique()

array([2, 3, 4, 6, 0, 1, 5, 7, 8, 9])

In [24]:
DataA_DF['Medio_Bano'].unique()

array([0, 1, 3, 2, 5, 4, 6, 7, 8])

In [26]:
DataA_DF['Estacionamientos'].unique()

array([2, 3, 4, 1, 0, 6, 5, 8, 7, 9])

In [27]:
DataA_DF["area"] = np.where((DataA_DF["Superficie_Terreno"] > DataA_DF["Superficie_Construida"])
                     ,DataA_DF["Superficie_Terreno"], DataA_DF["Superficie_Construida"])

In [ ]:
DataA_DF["Filtro"] = np.where((DataA_DF["Superficie_Terreno"] > DataA_DF["Superficie_Construida"])
                     ,"", DataA_DF["Superficie_Construida"])

In [28]:
Filtro = []
for i, row in DataA_DF.iterrows():
    Area = row["area"]
    #Columna Terreno
    try:
        if Area < 50:
            Filtro.append("NOK")
        else:    
            Filtro.append("OK")
    except:
        Filtro.append("NOK")

In [29]:
Filtro

['OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'NOK',
 'NOK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 

In [30]:
#DataBB = pd.DataFrame(Price_MXN,)
#DataBB = pd.DataFrame(Filtro,columns=['Filtro'])
DataA_DF.insert(0, 'Filtro', Filtro )
#DataAA_DF['Price MXN'] = Price_MXN 
DataA_DF

Filtro  Unnamed: 0        Marca Clasificacion   Tipo          Estado  \
0          OK           0  Inmuebles24          Casa  Venta  Aguascalientes   
1          OK           1  Inmuebles24          Casa  Venta  Aguascalientes   
2          OK           2  Inmuebles24          Casa  Venta  Aguascalientes   
3          OK           3  Inmuebles24          Casa  Venta  Aguascalientes   
4          OK           4  Inmuebles24          Casa  Venta  Aguascalientes   
...       ...         ...          ...           ...    ...             ...   
100683    NOK      105321  Inmuebles24  Departamento  Venta         Yucatán   
100684    NOK      105322  Inmuebles24  Departamento  Venta         Yucatán   
100685     OK      105324  Inmuebles24  Departamento  Venta         Yucatán   
100686     OK      105325  Inmuebles24  Departamento  Venta         Yucatán   
100687     OK      105326  Inmuebles24  Departamento  Venta         Yucatán   

          Municipio                            Colonia  \
0       Jesús María   Congregacion Corral de Barrancos   
1       Jesús María                         Maravillas   
2       Jesús María                         Maravillas   
3       Jesús María   Congregacion Corral de Barrancos   
4       Jesús María   Congregacion Corral de Barrancos   
...             ...                                ...   
100683       Mérida                           Cordemex   
100684       Mérida                      Montes de Ame   
100685       Mérida  Fraccionamiento Colonial Chuburna   
100686       Mérida  Fraccionamiento Colonial Chuburna   
100687       Mérida  Fraccionamiento Colonial Chuburna   

                                                 Colonia2  \
0                 Casa - Congregacion Corral de Barrancos   
1                En Venta Bonita Casa en Fracc Marcellana   
2                        Casa Nueva en El Álamo, Al Norte   
3       Casa en Corral de Barrancos, Jesús María, Agua...   
4                 Casa - Congregacion Corral de Barrancos   
...                                                   ...   
100683  Departamentos de Lujo en Venta en Harmonia Yuc...   
100684                       Departamento - Montes de Ame   
100685  Venta Departamentos 2 Habs con Amenidades en C...   
100686  Venta Departamentos con Amenidades en Col Chub...   
100687                                 Departamentos Loma   

                                                   Street  ... index_right  \
0       Coto DEL Sauce, Congregacion Corral de Barranc...  ...          93   
1                      parma 126, Maravillas, Jesús María  ...          93   
2                               , Maravillas, Jesús María  ...          93   
3         , Congregacion Corral de Barrancos, Jesús María  ...          93   
4       Venta Casa Nueva AL Norte EN Privada, Congrega...  ...          93   
...                                                   ...  ...         ...   
100683                                1, Cordemex, Mérida  ...          19   
100684  Desarrollo DE 9 Departamentos Ubicados EN LA C...  ...          19   
100685  Calle 24 E Entre Calle 19 y Calle 21 Colonia C...  ...          86   
100686  Calle 24 E Entre Calle 19 y Calle 21 Colonia C...  ...          86   
100687        , Fraccionamiento Colonial Chuburna, Mérida  ...          86   

         d_cp  OBJECTID_y  CVE_ENT_y  CVE_MUN_y  CVE_LOC_y  CVE_AGEB_y  \
0       20900         362          1          5       23.0        043A   
1       20900         362          1          5       23.0        043A   
2       20900         362          1          5       23.0        043A   
3       20900         362          1          5       23.0        043A   
4       20900         362          1          5       23.0        043A   
...       ...         ...        ...        ...        ...         ...   
100683  97110       60510         31         50        1.0        2324   
100684  97110       60510         31         50        1.0        2324   
100685  97215       60143

In [ ]:
Filtro = []
for i, row in DataA_DF.iterrows():
    area = int(row["area"])
    try:
        if Area > 50:
            New_Banos = Banos
            DataA_DF.at[i,'Estacionamientos'] = New_Banos
        else:
            #if len(Banos) == 1:
            New_Banos = Banos[0]
            DataA_DF.at[i,'Estacionamientos'] = New_Banos
            #else:
             #   pass
    except:
        New_Banos = Banos
        DataA_DF.at[i,'Estacionamientos'] = New_Banos

In [ ]:
DataA_DF.insert(0, 'Filtro', Filtro )
DataA_DF

In [31]:
DataA_DF.to_csv(f'Final_House_data2.csv', index=False, encoding='utf-8-sig')  

In [ ]:
Price_MXN = []
USD = "USD"
for i, row in DataAA_DF.iterrows():
    Moneda = str(row["Moneda"])
    #Columna Terreno
    try:
        if search(USD, Moneda):
            A = int(DataAA_DF.at[i,'PriceClean'])
            Price_MXN.append(A*21.5)
        else:
            A = int(DataAA_DF.at[i,'PriceClean'])
            Price_MXN.append(A)
    except:
        A = 0
        Price_MXN.append(A)